---
roles:

- src: https://github.com/ggatward/Ansible-RHEL7-CIS-Benchmarks.git
  scm: git

- src: https://github.com/ggatward/Ansible-RHEL8-CIS-Benchmarks.git
  scm: git

- src: https://github.com/ggatward/ansible-ipaclient.git
  scm: git

- src: https://github.com/adfinis-sygroup/ansible-role-hw_vm_tools.git
  scm: git

- src: https://github.com/ggatward/ansible-node-exporter.git
  scm: git

- src: https://github.com/ericsysmin/ansible-role-chrony.git
  scm: git

- name: ansible_nginx
  src: https://github.com/geerlingguy/ansible-role-nginx.git
  scm: git

- src: https://github.com/mrlesmithjr/ansible-config-interfaces.git
  scm: git

- src: https://github.com/mrlesmithjr/ansible-kvm
  scm: git

- src: https://github.com/ggatward/ansible-vdsm-prometheus.git
  scm: git


# - src: git@github.com:ggatward/ansible-role-workstation.git
#   scm: git
#   version: development



# - src: https://github.com/mrlesmithjr/ansible-keepalived.git
#   scm: git

# - src: https://github.com/mrlesmithjr/ansible-haproxy.git
#   scm: git

# - src: https://github.com/ggatward/ansible-grafana.git
#   scm: git
