---
roles:

- src: https://github.com/ggatward/Ansible-RHEL7-CIS-Benchmarks.git
  scm: git

- src: https://github.com/ggatward/Ansible-RHEL8-CIS-Benchmarks.git
  scm: git

- src: https://github.com/ggatward/ansible-ipaclient.git
  scm: git

- src: https://github.com/adfinis-sygroup/ansible-role-hw_vm_tools.git
  scm: git

- src: https://github.com/ericsysmin/ansible-role-chrony.git
  scm: git

- src: https://github.com/geerlingguy/ansible-role-nginx.git
  scm: git

- src: https://github.com/mrlesmithjr/ansible-config-interfaces.git
  scm: git

- src: https://github.com/mrlesmithjr/ansible-kvm
  scm: git

# - src: git@github.com:ggatward/ansible-role-workstation.git
#   scm: git
#   version: development

##### Prometheus and exporters #####
- src: https://github.com/cloudalchemy/ansible-prometheus.git
  scm: git

- src: https://github.com/cloudalchemy/ansible-pushgateway.git
  scm: git

- src: https://github.com/cloudalchemy/ansible-snmp-exporter.git
  scm: git

- src: https://github.com/cloudalchemy/ansible-blackbox-exporter.git
  scm: git

- src: https://github.com/cloudalchemy/ansible-alertmanager.git
  scm: git

- src: https://github.com/ggatward/ansible-collectd-exporter.git
  scm: git

- src: https://github.com/ggatward/ansible-statsd-exporter.git
  scm: git

- src: https://github.com/ggatward/ansible-node-exporter.git
  scm: git

# - src: https://github.com/ggatward/ansible-vdsm-prometheus.git
#   scm: git

- src: https://github.com/ggatward/ansible-389ds-exporter.git
  scm: git

- src: https://github.com/ggatward/ansible-ovirt-exporter.git
  scm: git

- src: https://github.com/ggatward/ansible-ipmi-exporter.git
  scm: git
